### ISSUE TITLE
npm run develop throws ELIFECYCLE ERR 1 system cannot find the path specified

### ISSUE THREAD

**Issue by blazephoenix** [tanaypratap/teamtanay.jobchallenge.dev#348]
```
npm run develop

The system cannot find the path specified.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! teamTanayJobChallenge@0.1.0 start: `npm run develop`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the teamTanayJobChallenge@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\naikt\AppData\Roaming\npm-cache\_logs\2020-04-14T09_18_45_339Z-debug.log
```

Yarn causes different issues related to the sharp module so I'm using npm. Since the last time I used gatsby, I used it with npm and it worked fine. The log file doesn't seem to give any useful information either.

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\naikt\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.13.2
3 info using node@v12.16.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle teamTanayJobChallenge@0.1.0~prestart: teamTanayJobChallenge@0.1.0
6 info lifecycle teamTanayJobChallenge@0.1.0~start: teamTanayJobChallenge@0.1.0
7 verbose lifecycle teamTanayJobChallenge@0.1.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle teamTanayJobChallenge@0.1.0~start: PATH: C:\Users\naikt\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;B:\Code\job-challenge\teamtanay.jobchallenge.dev\node_modules\.bin;C:\Program Files (x86)\ImageMagick-6.9.10-Q16;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MongoDB\Server\4.0\bin;C:\sqlite3;C:\Program Files\dotnet\;C:\Users\naikt\AppData\Local\Programs\Python\Python37-32\;C:\Users\naikt\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\naikt\AppData\Roaming\Python\Python37\Scripts;C:\Program Files\Git\cmd;C:\wamp64\bin\php\php7.2.4;C:\ProgramData\ComposerSetup\bin;C:\Program Files (x86)\Tesseract-OCR;C:\Program Files\PostgreSQL\bin;C:\Users\naikt\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files\heroku\bin;C:\Program Files (x86)\ImageMagick-6.9.10-Q16;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files\Intel\iCLS Client\;C:\windows\system32;C:\windows;C:\windows\System32\Wbem;C:\windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\MongoDB\Server\4.0\bin;C:\sqlite3;C:\Program Files\dotnet\;C:\Users\naikt\AppData\Local\Programs\Python\Python37-32\;C:\Users\naikt\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\naikt\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\naikt\AppData\Roaming\npm
9 verbose lifecycle teamTanayJobChallenge@0.1.0~start: CWD: B:\Code\job-challenge\teamtanay.jobchallenge.dev
10 silly lifecycle teamTanayJobChallenge@0.1.0~start: Args: [ '/d /s /c', 'npm run develop' ]
11 silly lifecycle teamTanayJobChallenge@0.1.0~start: Returned: code: 1  signal: null
12 info lifecycle teamTanayJobChallenge@0.1.0~start: Failed to exec start script
13 verbose stack Error: teamTanayJobChallenge@0.1.0 start: `npm run develop`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\naikt\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:311:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\naikt\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:311:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid teamTanayJobChallenge@0.1.0
15 verbose cwd B:\Code\job-challenge\teamtanay.jobchallenge.dev
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\naikt\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
18 verbose node v12.16.1
19 verbose npm  v6.13.2
20 error code ELIFECYCLE
21 error errno 1
22 error teamTanayJobChallenge@0.1.0 start: `npm run develop`
22 error Exit status 1
23 error Failed at the teamTanayJobChallenge@0.1.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by blazephoenix** [comment]
Figured that the error is with the sharp module. Did everything suggested on the Gatsby site, but the error wont resolve

**Comment by gkanishk** [comment]
@blazephoenix so it's resolved right??

**Comment by blazephoenix** [comment]
> @blazephoenix so it's resolved right??

No, I just edited the Markdown file and pushed anyway. Since the problem is just on my machine, I figured it won't cause any issues if I do that

**Comment by gkanishk** [comment]
Cool if you figured out or have resolved then kindly close this issue
